### ISSUE TITLE
Empty filter box on filter reset

### ISSUE THREAD

**Issue by OllieintheUK** [okviz/smart-filter-pro-issues#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi I really like the use of this slicer above any other available on Power BI. However, there is one bug bear I have and haven't been able to find a workaround for. I have many reports with multiple instances of the smart filter included. In these, I often get requests to include a 'clear filters' button, which I usually use a bookmark for. Unfortunately, whilst the filter control resets and returns to an unfiltered view, the previous items are left in the filter box. This makes it very confusing to understand what, if any filters are currently active in a given view.

### Power BI

Power BI Desktop, Power BI service

### Power BI Version

November (but every version for the last couple years)

### Steps To Reproduce

Have a bookmark that returns a report to an unfiltered view. Apply multiple filters, hit the bookmark.

### Sample report

[Example Smart Filter Issue.zip](https://github.com/okviz/smart-filter-pro-issues/files/14013321/Example.Smart.Filter.Issue.zip)

**Comment by danieleperilli** [comment]
Unfortunately, Smart Filter Free doesn't support bookmarks. You need to switch to Pro version to enable them.

**Comment by OllieintheUK** [comment]
@danieleperilli, thanks for the swift response. I am slightly confused still. To confirm, if I were to use a pro licence, the box would indeed clear on use of a bookmark or other page reset process? 

Do you have any videos demonstrating the pro version etc to confirm this?

Thanks

**Comment by danieleperilli** [comment]
You can try the visual for free, so to verify the feature works as expected.

**Comment by OllieintheUK** [comment]
You've lost me again? I am ofcourse already making heavy use of the free version?! I wish to confirm the functionality change mentioned in the pro version as I previously read it simply provides access to added features/customisability rather than a structural change in the way it operates.

**Comment by danieleperilli** [comment]
You can try the **PRO** version for free.

**Comment by OllieintheUK** [comment]
Apologies, I didn't realise the Pro version is available to test offline. I thought it was the same plugin not a separate download. I see that works as described, thanks. 

Final question, my company very rarely allow uncertified visuals on published tools, is there any reason why the pro filter version is uncertified but all other OKViz visuals are certified?

Thanks once again

**Comment by danieleperilli** [comment]
No problem. Yes, there is a valid reason why Smart Filter Pro is not certified; please look at this page: https://docs.okviz.com/smart-filter-pro/security
