### ISSUE TITLE
Unlock the premium

### ISSUE THREAD

**Issue by BrTarsis** [okviz/smart-filter-pro-issues#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

I had a problem with unlocking, apparently the license was not recognized. Follow print
image.png
![image (6)](https://github.com/okviz/smart-filter-pro-issues/assets/87377926/5607e44f-e22e-45df-833a-cacfa993cca4)

### Power BI

Power BI Desktop

### Power BI Version

Versão: 2.124.1805.0 64-bit (dezembro de 2023)

### Sample report

The problem is related to the password to unlock the premium.

### Screenshot

![image (6)](https://github.com/okviz/smart-filter-pro-issues/assets/87377926/259b8eab-780f-4f9d-b566-547b2501dc33)

**Comment by danieleperilli** [comment]
Wrong repo. This is for a premium custom visual. If have already sent an email to the customer support, please patiently wait for their response.
